//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dufeksoft.lib.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DufeksoftLibResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DufeksoftLibResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dufeksoft.lib.Localization.DufeksoftLibResource", typeof(DufeksoftLibResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ContactRequestCultureId {
            get {
                return ResourceManager.GetString("ContactRequestCultureId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message: {0}.
        /// </summary>
        public static string ContactRequestSubject {
            get {
                return ResourceManager.GetString("ContactRequestSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactSendSuccess.
        /// </summary>
        public static string ContactRequestTemplate {
            get {
                return ResourceManager.GetString("ContactRequestTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid e-mail.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string LabelConfirmPassword {
            get {
                return ResourceManager.GetString("LabelConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string LabelEmail {
            get {
                return ResourceManager.GetString("LabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending the message. Correct errors and try again..
        /// </summary>
        public static string LabelErrorInfo {
            get {
                return ResourceManager.GetString("LabelErrorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write us a message.
        /// </summary>
        public static string LabelHeader {
            get {
                return ResourceManager.GetString("LabelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message has been sent..
        /// </summary>
        public static string LabelMsgSent {
            get {
                return ResourceManager.GetString("LabelMsgSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your message here.
        /// </summary>
        public static string LabelMsgText {
            get {
                return ResourceManager.GetString("LabelMsgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string LabelName {
            get {
                return ResourceManager.GetString("LabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LabelPassword {
            get {
                return ResourceManager.GetString("LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will contact You as soon as possible..
        /// </summary>
        public static string LabelSeeYouSoon {
            get {
                return ResourceManager.GetString("LabelSeeYouSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string LabelSend {
            get {
                return ResourceManager.GetString("LabelSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string LabelSubject {
            get {
                return ResourceManager.GetString("LabelSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You for contacting us..
        /// </summary>
        public static string LabelThankYou {
            get {
                return ResourceManager.GetString("LabelThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail is required.
        /// </summary>
        public static string RequiredEmail {
            get {
                return ResourceManager.GetString("RequiredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message text is required.
        /// </summary>
        public static string RequiredMsgText {
            get {
                return ResourceManager.GetString("RequiredMsgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string RequiredName {
            get {
                return ResourceManager.GetString("RequiredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject is required.
        /// </summary>
        public static string RequiredSubject {
            get {
                return ResourceManager.GetString("RequiredSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount in € to pay.
        /// </summary>
        public static string TatraCardPayLabelAmount {
            get {
                return ResourceManager.GetString("TatraCardPayLabelAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name and surname.
        /// </summary>
        public static string TatraCardPayLabelName {
            get {
                return ResourceManager.GetString("TatraCardPayLabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice number.
        /// </summary>
        public static string TatraCardPayLabelVs {
            get {
                return ResourceManager.GetString("TatraCardPayLabelVs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount can&apos;t be empty. Enter an amount to pay in €..
        /// </summary>
        public static string TatraCardPayRequiredAmount {
            get {
                return ResourceManager.GetString("TatraCardPayRequiredAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name can&apos;t be empty..
        /// </summary>
        public static string TatraCardPayRequiredName {
            get {
                return ResourceManager.GetString("TatraCardPayRequiredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice number can&apos;t be empty..
        /// </summary>
        public static string TatraCardPayRequiredVs {
            get {
                return ResourceManager.GetString("TatraCardPayRequiredVs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only numeric value with two decimal places is allowed..
        /// </summary>
        public static string TatraCardPayWrongAmount {
            get {
                return ResourceManager.GetString("TatraCardPayWrongAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed characters are 0-9, a-z,
        ///A-Z, space, dot,
        ///&apos;-&apos;, &apos;_&apos;, &apos;@&apos;.
        /// </summary>
        public static string TatraCardPayWrongName {
            get {
                return ResourceManager.GetString("TatraCardPayWrongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only numeric character are allowed..
        /// </summary>
        public static string TatraCardPayWrongVs {
            get {
                return ResourceManager.GetString("TatraCardPayWrongVs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced payment.
        /// </summary>
        public static string TbCardPayAdvancePayment {
            get {
                return ResourceManager.GetString("TbCardPayAdvancePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string TbCardPayBtnSend {
            get {
                return ResourceManager.GetString("TbCardPayBtnSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct errors and try again..
        /// </summary>
        public static string TbCardPayErrTitle {
            get {
                return ResourceManager.GetString("TbCardPayErrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment form.
        /// </summary>
        public static string TbCardPayFormTitle {
            get {
                return ResourceManager.GetString("TbCardPayFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string TbCardPayLang {
            get {
                return ResourceManager.GetString("TbCardPayLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The payment failed..
        /// </summary>
        public static string TbCardPayPaymentFailed {
            get {
                return ResourceManager.GetString("TbCardPayPaymentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing security token in response. Please contact us..
        /// </summary>
        public static string TbCardPayPaymentNoSecInfo {
            get {
                return ResourceManager.GetString("TbCardPayPaymentNoSecInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The payment processed successfully..
        /// </summary>
        public static string TbCardPayPaymentOk {
            get {
                return ResourceManager.GetString("TbCardPayPaymentOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again later or contact us..
        /// </summary>
        public static string TbCardPayPaymentTryLater {
            get {
                return ResourceManager.GetString("TbCardPayPaymentTryLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security check error. Please contact us..
        /// </summary>
        public static string TbCardPayPaymentWrongSecInfo {
            get {
                return ResourceManager.GetString("TbCardPayPaymentWrongSecInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect to payment gateway. Please wait ....
        /// </summary>
        public static string TbCardPayRedirectingToGateway {
            get {
                return ResourceManager.GetString("TbCardPayRedirectingToGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string TbCardPayRegularPayment {
            get {
                return ResourceManager.GetString("TbCardPayRegularPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To make a safe payment you will be redirected to the Tatrabanka bank payment gate where we have our bank account. When the payment finishes you will be redirected back to oktrip.sk web pages..
        /// </summary>
        public static string TbCardPaySecureInfo {
            get {
                return ResourceManager.GetString("TbCardPaySecureInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill the form below to make a payment..
        /// </summary>
        public static string TbCardPaySubTitle {
            get {
                return ResourceManager.GetString("TbCardPaySubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string TbCardPayTitle {
            get {
                return ResourceManager.GetString("TbCardPayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced payment.
        /// </summary>
        public static string VubAdvancePayment {
            get {
                return ResourceManager.GetString("VubAdvancePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string VubBtnSend {
            get {
                return ResourceManager.GetString("VubBtnSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct errors and try again..
        /// </summary>
        public static string VubErrTitle {
            get {
                return ResourceManager.GetString("VubErrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment form.
        /// </summary>
        public static string VubFormTitle {
            get {
                return ResourceManager.GetString("VubFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount in € to pay.
        /// </summary>
        public static string VubLabelAmount {
            get {
                return ResourceManager.GetString("VubLabelAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice number.
        /// </summary>
        public static string VubLabelOid {
            get {
                return ResourceManager.GetString("VubLabelOid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string VubLang {
            get {
                return ResourceManager.GetString("VubLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect to payment gateway. Please wait ....
        /// </summary>
        public static string VubRedirectingToGateway {
            get {
                return ResourceManager.GetString("VubRedirectingToGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string VubRegularPayment {
            get {
                return ResourceManager.GetString("VubRegularPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount can&apos;t be empty. Enter an amount to pay in €..
        /// </summary>
        public static string VubRequiredAmount {
            get {
                return ResourceManager.GetString("VubRequiredAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice number can&apos;t be empty..
        /// </summary>
        public static string VubRequiredOid {
            get {
                return ResourceManager.GetString("VubRequiredOid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To make a safe payment you will be redirected to the VUB bank payment gate where we have our bank account. When the payment finishes you will be redirected back to oktrip.sk web pages..
        /// </summary>
        public static string VubSecureInfo {
            get {
                return ResourceManager.GetString("VubSecureInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill the form below to make a payment..
        /// </summary>
        public static string VubSubTitle {
            get {
                return ResourceManager.GetString("VubSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string VubTitle {
            get {
                return ResourceManager.GetString("VubTitle", resourceCulture);
            }
        }
    }
}
